server:
  port: 10000
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/fer
    username: postgres.kuetkyfnvqtohzwulujy
    password: Cocolyu1988719
  messages:
    basename: i18n/messages
logging:
  level:
    mingle.chang: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: input
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true

custom:
  oss:
    region: xsd/ODp6iFL34CyzFrY=
    end-point: xsd/ODp6iFL34CyzFrZs4TbrX5HxVlivbVa/
    access-key-id: 5eBNXG1T5EnZwgjiR6s25mjxTdbxRx3k
    access-key-secret: 4YB2RB1xl0jFtRCAN5kl723GEKXuQB+2VwqHiKEN
    bucket: z91gcHR4ykf64yemX6As
  exchange-rate:
    fixer-io:
      access-key: 97bebd88d1459e3b8ad1325e237f0ecd
      host: https://data.fixer.io
      symbols-endpoint: /api/symbols
      latest-endpoint: /api/latest
      historical-endpoint: /api/

